### ISSUE TITLE
I'm trapped in assert( v != u && "1: floating point precision error");

### ISSUE THREAD

**Issue by msokalski** [eloraiby/delaunay#13]
My point cloud input seams to be far from degenerated but triangulation fails with "1: floating point precision error" assert. Please find dataset attached.
[delanuay-in.txt](https://github.com/eloraiby/delaunay/files/2159470/delanuay-in.txt)

**Comment by eloraiby** [comment]
Need the following information:
- Arch/Processor
- Floating point resolution/type (`32/float | 64/double | 80/long double`)

**Comment by msokalski** [comment]
- x64/Intel i5
- 64/double
- vs2017

**Comment by eloraiby** [comment]
using the program found in `example`, your dataset was handled without problem. The only required modification was to add spaces to `fscanf` like the following: `fscanf(file, "%lf , %lf", &pt.x, &pt.y);`.
