### ISSUE TITLE
[Feature Request] - Constraining output to triangles only 

### ISSUE THREAD

**Issue by dharmendra08** [eloraiby/delaunay#2]
Hi,
  Delaunay technique is for making triangles from given points. Example Image posted by you in Readme.md shows squares instead of triangles, which clearly hints OnCircle point case is not taken.

**Comment by eloraiby** [comment]
You can have a delaunay "face" that is a polygon as long as all the points are on circle. Do you want to constrain the output to triangles only ?

**Comment by dharmendra08** [comment]
Yeah, right.. I want to constrain output to triangles. I think for that I have to consider circle case. I have edited the code and now its pretty much working for grid. Following figure shows expected output:

![image](https://cloud.githubusercontent.com/assets/2807206/3225663/d94e7b16-f057-11e3-9f45-155d427b1a9c.png)

Image Source: http://www.cs.unc.edu/~snoeyink/demos/crust/home.html
EDIT:
Subject changed to : "Constraining output to triangles only".

**Comment by eloraiby** [comment]
implemented!
