### ISSUE TITLE
Assertation "floating point precision error" when compiled with -O1, -O2 or -O3 in 32 bit mode

### ISSUE THREAD

**Issue by uranix** [eloraiby/delaunay#3]
I'm getting

```
delaunay.c:690: del_valid_left: Assertion `v != u && "1: floating point precision error"' failed.
```

when using FAST_PREDICATE or EXACT_PREDICATE and

```
delaunay.c:754: del_valid_right: Assertion `du->pair' failed.
```

when using LOOSE_PREDICATE.
Code was built with gcc (Debian 4.9.2-10) and `-m32` switch with any of `-O1`, `-O2`, `-O3`. 

Enabling SSE2 via `-msse2 -mfpmath=sse` seems to solve the problem. The failing test is [here](https://github.com/uranix/delaunay/tree/failing)

**Comment by eloraiby** [comment]
thanks for the test case, I ll be checking on it ASAP!

**Comment by eloraiby** [comment]
removed float/double and defaulting to long double. Please test and confirm

**Comment by uranix** [comment]
Worked like a charm, thank you
