### ISSUE TITLE
Delanunay Triangulation

### ISSUE THREAD

**Issue by san4esv1995** [eloraiby/delaunay#4]
Hellow, I need a help to solve a problem using Del.Triang. Can you help me to write a small programm on C++ (QtCreator). At the entrance I have massive an array of points (2D coordinates), that must be triangulated. And output array of elemets.
(Student of second grade of Saint-Petersburg Polytechnic University)
In advance thank you.

**Comment by eloraiby** [comment]
I cannot do your homework for you. read the code example as it cannot be simpler than that.
